### ISSUE TITLE
Not able to Query Record with where clause

### ISSUE THREAD

**Issue by lokendrajhala** [forcedotcom/SalesforceMobileSDK-Android#1056]
I am using the following query to get Asset 

`String soql="SELECT {Asset:Name},{Asset:Description} FROM {Asset} WHERE {Asset:RecordTypeId}= '0124B0000000D4fQAE'";`

```
final QuerySpec querySpec = QuerySpec.buildSmartQuerySpec(soql,LIMIT);
results = smartStore.query(querySpec, 0);
```

I am getting the following error

` com.salesforce.androidsdk.smartstore.store.SmartSqlHelper$SmartSqlException: Asset does not have an index on RecordTypeId at character 59`
                                                                      
Its working fine if i remove the where clause
My Index spec for soup is  
```
 private static IndexSpec[] ASSET_INDEX_SPEC = {
		new IndexSpec("Id", Type.string),
		new IndexSpec("Name", `Type.string),`
		new IndexSpec("Description", Type.string),
		new IndexSpec("RecordTypeId",Type.string),
		new IndexSpec(SyncManager.LOCALLY_CREATED, Type.string),
		new IndexSpec(SyncManager.LOCALLY_UPDATED, Type.string),
		new IndexSpec(SyncManager.LOCALLY_DELETED, Type.string),
		new IndexSpec(SyncManager.LOCAL, Type.string)
	};
```

Thanks for your help.

**Comment by wmathurin** [comment]
If you already launched the application and logged in, then change the index specs and restart the application, the soup won't get the new index specs.
You have two options: 
- logout and log back in (that causes the database to be recreated) <- this is the recommended approach during development
- call alterSoup instead of registerSoup from your code if the soup already exists <- this is the path to take when distribution a new version of the application to the app store to make the upgrade easy on users.
