### ISSUE TITLE
After creating project using forcedroid getting manifest merge issue.

### ISSUE THREAD

**Issue by asinha08** [forcedotcom/SalesforceMobileSDK-Android#1074]
D:\........\platforms\android\AndroidManifest.xml:30:9 Error:
        Element activity#com.adobe.phonegap.push.PushHandlerActivity at AndroidManifest.xml:30:9 duplicated with element declared at AndroidManifest.xml:6:9
D:\.........\platforms\android\AndroidManifest.xml:0:0 Error:
        Validation failed, exiting
:processDebugManifest FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED
 
Total time: 22.615 secs
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1

**Comment by jayadaadrit** [comment]
Facing the same issue..

**Comment by wmathurin** [comment]
What version of the sdk are you using? What version of cordova cli are you running? And finally, what version of shelljs do you have on your system?

**Comment by jayadaadrit** [comment]
Sorry for late response :)
Versions are as follows-
com.salesforce(plugin): 4.1.1
cordova version: 6.0.0
forcedroid version: 4.1.1

**Comment by jayadaadrit** [comment]
I'm stuck! can you please reply fast :(

**Comment by kchitalia** [comment]
Can you please provide us with the shelljs version?

**Comment by jayadaadrit** [comment]
shelljs 0.5.3
I don't know why I've to mention this? it comes with forcedroid.

**Comment by toddhalfpenny** [comment]
Hey, do you have any other plugins installed? I've found that if I do then the order of installation is important.

**Comment by jayadaadrit** [comment]
com.salesforce 4.1.1 "SalesforceMobileSDK Plugins"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-media 2.2.0 "Media"
cordova-plugin-whitelist 1.2.1 "Whitelist"
de.sitewaerts.cordova.documentviewer 0.2.0 "SitewaertsDocumentViewer"
phonegap-plugin-push 1.5.3 "PushPlugin"

Whitelist is default one.

**Comment by toddhalfpenny** [comment]
Ok, you could try, removing and re-adding the Salesforce plugin after adding the others, and then add the platform.
Adding the Salesforce plugin last seems to work for us.

**Comment by jclark-dot-org** [comment]
@toddhalfpenny At the moment I'm just trying to build an empty project with no additional plugins, and that's enough to run into the duplicate entries issue, once `cordova prepare android` runs an extra time.  For example:

    forcedroid create --apptype=hybrid_remote --appname=sdktest --targetdir=. --packagename=org.jclark.sdktest --startpage=/apex/BasicVFPage
    cd sdktest
    cordova prepare android
    cordova build android 

produces the duplicate entries error.  **note** based on [this][1], my local forcedroid has been edited to use a specific commit from unstable to avoid the push plugin SENDER_ID error, like so:

    shelljs.exec('cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#a45425d8e831c9567a0d0bf8b05bc3e1b19b4f23');

I tried to remove and re-add the SDK plugin, but the Push Plugin is a dependency of the SDK and gets removed and re-added along with the SDK, so I'm not sure that's fixing the ordering as desired.

I also tried adding the MobileSDK's dependencies directly, so that the SDK could in fact be the last plugin, like so:  

    forcedroid create --apptype=hybrid_remote --appname=sdktest --targetdir=. --packagename=org.jclark.sdktest --startpage=/apex/BasicVFPage
    cd sdktest
    cordova platform remove android
    cordova plugin remove com.salesforce
    cordova plugin add cordova-plugin-device@1.0.1
    cordova plugin add https://github.com/phonegap/phonegap-plugin-push\#1.5.0
    cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin\#a45425d8e831c9567a0d0bf8b05bc3e1b19b4f23
    cordova platform add android@5.0.0
    cordova prepare android
    cordova build android

This still gives me the duplicate entry message.  Perhaps with other plugins present, removing and re-adding the SF plugin results in a different result. 

My current workaround is:
1.  Remove the second occurance of the push plugin activity in AndroidManifest.xml
2.  Edit android.json, find the line for the PushHandler activity, and add `android:launchMode=\"singleTop\"`.  This seems to prevent `cordova prepare` from thinking that the Activity is missing and re-adding it.

[1]: https://plus.google.com/106416138732002084790/posts/RHKzqZXFgdt

**Comment by toddhalfpenny** [comment]
Aha... you're using `cordova build`, sorry I missed that. I too am also unable to get a build working like that, and have moved to currently using, following `cordova prepare`, gradle commands instead (or opening in Android Studio and building from there). These commands seem to work for me (it's either build or assemble, I can't remember which at the mo, or maybe both).

```
cd platforms/android
./gradlew build
./gradlew assemble
```

**Comment by jclark-dot-org** [comment]
Ah, I have not tried directly running gradle.  Couldn't get that to work with the project where I manually fiddled with android.json, but creating a brand new empty project, and using gradle produces an app that builds and runs (again, with my patched forcedroid to avoid SENDER_ID errors, see earlier comment):

    forcedroid create --apptype=hybrid_remote --appname=sdktest --targetdir=. --packagename=org.jclark.sdktest --startpage=/apex/BasicVFPage
    cd sdktest/platforms/android
    ./gradlew assemble
    ./gradlew installDebug

This generated a number of errors of the form, "WARNING: Dependency org.apache.httpcomponents:httpclient:4.3.2 is ignored for debug as it may be conflicting with the internal version provided by Android.", but it generated an installed a working hybrid mobile app.  So it definitely seems that something is not working correctly in the `cordova prepare`/`cordova build` workflow.

Now to see if I can retrofit these learnings onto my real app, which I recently rebuilt from a 3.x built to a 4.1 build.

**Comment by meckert-salesforce** [comment]
I'm fighting with the same issue.  Looks like it actually might be a general cordova issue with the merging of manifest entries when the same features are requested by different plugins but with different settings:
https://issues.apache.org/jira/browse/CB-8401
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/295

**Comment by helenren** [comment]
using 
com.salesforce 4.1.2 "SalesforceMobileSDK Plugins"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-push 1.5.0 "PushPlugin" I cannot repro the issue, the created app build successfully. While, Once I upgrade the pushplugin from 1.5.0 to 1.6.4, repro your issue exactly. Seems there is a issue in that plugin since version 1.5.3. To unblock you, could you please move back to older version 1.5.0?

**Comment by huminzhi** [comment]
In latest version, 4.1.2, it restricted to use phonegap-plugin-push 1.5.0, so please use v1.5.0.

**Comment by helenren** [comment]
Do you have any specific function you need to you newer version of that push plugin, if so, that will be a feature request, and we can work to support newer version. Please let us know. Thanks.
