### ISSUE TITLE
Issue with mobile push registrations for Android native apps

### ISSUE THREAD

**Issue by karsrini1973** [forcedotcom/SalesforceMobileSDK-Android#1093]
We have an Android native application used by community users of our org. Our Salesforce backend pushes android notifications to active community users when there is new/updated user specific data available. 

We have deployed our package and distributed tablets running our native application to our customers. Post deployment we notice that for some of the users, the push notifications stop working. On further analysis we noticed that for these users the Mobile Push Registrations show up as empty. Also, from the logs, we can see that the notification send has failed with the error PUSH_NOTIFICATION_NO_DEVICES. 

We have raised a case for this: Case 13281412. We got to know that push registrations are expired every 45 days and unfortunately, the current re-registration behavior built into the mobile SDK does not work for us for the below detail(s) - please also see the referred case for more detailed information. 

In our native application, users login only once. The oAuth refresh token is set not to expire and access token refresh is automatically handled by Salesforce Mobile SDK. Also, our users are likely to restart the tablet regularly - this clears any retry related alarms setup by Mobile SDK. Once a restart happens, the Push Service never gets triggered. Due to this re-registration no longer happens. 

We want to understand 
a) The rationale behind expiry of mobile push registrations (even if the user is active)?  And why is there no clear documentation of this behavior? 
b) Is there any way to remotely re-activate the registration (without having to revoke the user)? We have already on-boarded quite a few users with our app on the field and are looking for any work around that could be rolled out without an APK upgrade in the short term. 
c) What should be the standard app behavior in these cases? Particularly when we have only a one time login and regular tablet restarts.  
d) Can we receive some sort of notification at the client side if the push registration is no longer valid? 
e) Can mobile SDK offer some additional support to handle cases like ours? (de-couple registration from login flow and enable the re-registration attempts to be triggered even if there is no login on re-start). 

Thanks,
Karthik﻿

**Comment by bhariharan** [comment]
Thanks for the detailed explanation.

a) Expiry of mobile push registrations has been implemented on the Salesforce server side. The client (Mobile SDK) has no control over this behavior, which is why we attempt to re-register periodically.
b) Unfortunately, there's no way to workaround this without pushing a client side update.
c) We will look at the re-registration flow from our end, to ensure it handles the device restart use case and other similar cases. Meanwhile, the simplest way for the app to handle this situation would probably be to call ```PushMessaging.register...``` every time the app is initialized (after ```SalesforceSDKManager.init...``` call).
d) Unfortunately, the server doesn't send us a notification if the user has been unregistered, so there's nothing we can do in Mobile SDK.
e) ```PushMessaging.register...``` and ```PushMessaging.unregister...``` APIs exist for this reason. There are other public APIs in ```PushMessaging``` too, for specific actions, such as the Salesforce portion of registration.

**Comment by karsrini1973** [comment]
Thanks Bharath. So - the only approach for us is to immediately make the
necessary changes in our app (to call PushMessaging.register) on every
startup - at the least.

We will look at incorporating this as an immediate mitigation. Do let us
know of any update to the re-registration flow at mobile SDK level - so
that if a patch becomes available, we can incorporate the same in our
future releases...

Regards,
Karthik

On Wed, Mar 30, 2016 at 3:45 AM, Bharath Hariharan <notifications@github.com

**Comment by bhariharan** [comment]
This should be fixed in `Mobile SDK 5.2`.

**Comment by MohitNagori** [comment]
Hi Bharath
We are facing this issue in version 6.0 even after updating sdk to latest version

**Comment by vinod1988** [comment]
@bhariharan @wmathurin 
Can I explicitly register this in my Android and iOS React Native app for push notifications?
