### ISSUE TITLE
Customize Login Screen

### ISSUE THREAD

**Issue by TRPCindy** [forcedotcom/SalesforceMobileSDK-Android#1105]
Hi, is there a way to customize the login screen of the react native salesforce app?

**Comment by wmathurin** [comment]
Yes it can be done from the java code.

If you just want to change the layout, provide a sf__login.xml layout in your application and it should be picked up instead of the one that comes with the SDK.

If you need to do more than change the layout then change the SalesforceReactSDKManager.init call in your application class (the class called <YourAppName>ReactNativeApp.java) to:

```java
SalesforceReactSDKManager.initReactNative(getApplicationContext(), new ReactNativeKeyImpl(), MainActivity.class, YourLoginActivity.class);
```
