### ISSUE TITLE
support dynamic version of react-native

### ISSUE THREAD

**Issue by realdoug** [forcedotcom/SalesforceMobileSDK-Android#1357]
Looks like SDK requires a specific version of react-native.  It would be nice if the developer could specify which version of react native that they are using.

https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/build.gradle

**Comment by bhariharan** [comment]
@realdoug It is hard to guarantee compilation of our libraries without specifying a dependent version, since `react-native` is iterating quickly and breaks API pretty often. With every `Mobile SDK` release, we do bump up to the latest `react-native` version. Meanwhile, you're welcome to bump it up in your app on your fork of `Mobile SDK`. Or you could consume the bleeding edge from our `dev` branch.

**Comment by realdoug** [comment]
@bhariharan i noticed that the most recent release was 6 days ago, but the react native version is still 0.35 (as was set in the 5.0.0 release).  Is this intentional?  When do you expect the next version bump to be?

**Comment by bhariharan** [comment]
Our `5.0.0` release went out a couple of months ago. We will bump it up on the `dev` branch pretty soon. I don't have an exact timeframe for you, unfortunately.

**Comment by realdoug** [comment]
Thanks.  If I were to fork & update version, is it just the build.gradle file that i linked to above and the package.json?  Anywhere else i need to change?

**Comment by bhariharan** [comment]
That should be it. Once you do that, run `. install.sh` from the root of the repo to sync and pull those versions.
