### ISSUE TITLE
react.force.common.js does not exist

### ISSUE THREAD

**Issue by karthik2391** [forcedotcom/SalesforceMobileSDK-Android#1393]
1. Version of Mobile SDK Used:  5.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version:Android 25
4. Device:Android
5. Steps to reproduce: run cscript install.vbs after cloning SDK  file  from  git
6. Actual behavior: react.force.common.js does not exist
7. Expected Behavior: Should install
8. Error Log: Source file 'external\shared\libs\react.force.common.js' does not exist!  Cannot continue.

**Comment by wmathurin** [comment]
Thanks for reporting the issue - we will look at it.

**Comment by wmathurin** [comment]
The fix for dev is on that PR: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1394
Either check out the dev branch (once the PR is merged)
Or wait for 5.1 to go live (should be later this month)
Or cherry pick/apply the fix to your repo (but since a few things have moved around, you will need to run ./tools/build_windows_file_list.js to regenerate the links file).

Thanks.
