### ISSUE TITLE
ConnectUriBuilder uses ApiVersionStrings.getBaseChatterPath() as base url

### ISSUE THREAD

**Issue by LyndonChin** [forcedotcom/SalesforceMobileSDK-Android#1429]
Please fill out the following details:

1. Version of Mobile SDK Used: commit 3ac504391db7dee94526c01ad902549a4d11588e
2. Issue found in Native App or Hybrid App: Native
3. OS Version: -
4. Device: 
5. Steps to reproduce: read the source
6. Actual behavior: `this(Uri.parse(ApiVersionStrings.getBaseChatterPath()).buildUpon());`
7. Expected Behavior: `this(Uri.parse(ApiVersionStrings.getBaseConnectPath()).buildUpon());`
8. Error Log:

**Comment by LyndonChin** [comment]
![image](https://user-images.githubusercontent.com/6782576/26869048-9782bba8-4b9d-11e7-8fa8-87dfde7d6469.png)

**Comment by bhariharan** [comment]
@LyndonChin I don't think this is a bug. The naming convention here is a bit misleading, but we do want the base path to be `baseChatterPath` by default here since it's used to file APIs (look [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/files/ApiRequests.java#L51) and [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/files/FileRequests.java#L71)). We have tests [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/rest/files/ConnectUriBuilderTest.java#L43) that look for that path too. This is by design, but I agree that the naming convention is a bit weird here.
