### ISSUE TITLE
SmartSync cannot do async syncDown

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-Android#1517]
Please fill out the following details:

1. Version of Mobile SDK Used: 
V5.2.0

2. Issue found in Native App or Hybrid App:
Hybrid

3. OS Version:
Android 5.1

4. Device:
Emulator

5. Steps to reproduce:
(1) Execute two syncDowns for different soups

6. Actual behavior:
The syncDown executed one by one

7. Expected Behavior:
Two syncDown should run in the same time instead of sequential

8. Error Log:

9. Further information:
Async syncDown is working on iOS

**Comment by wmathurin** [comment]
It's by design, see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java#L83). We are using a thread pool of one.
We could allow more threads, but you have to be aware that sqlite (SmartStore uses SQLCipher which is based on sqlite) does not allow concurrent writes - so even if we allow more threads in SyncManager, things will not be completely parallelized.

**Comment by booker-laputa** [comment]
I see but I think iOS is using SQLCipher too and it allows concurrent writes?

**Comment by wmathurin** [comment]
Look at question (5) [here](https://sqlite.org/faq.html).

> SQLite allows multiple processes to have the database file open at once, and for multiple processes to read the database at once. When any process wants to write, it must lock the entire database file for the duration of its update.

The Mobile SDK is open source, so you could fork it, and bump up the size of the thread pool and see how it helps in your application.
