### ISSUE TITLE
SPRequestHandler tightly coupled to LoginActivity

### ISSUE THREAD

**Issue by methodus** [forcedotcom/SalesforceMobileSDK-Android#1671]
Version of Mobile SDK Used: 6.1.0

I cloned the com.salesforce.androidsdk.ui.LoginActivity to my own LoginActivity to customize the layout and behavior. However, I had remove the IDP login functions because the SPRequestHandler is tightly coupled to the default LoginActivity.SPAuthCallback. I can't create an overloaded callback, because SPAuthCallback is not an interface nor static, so it's not an enclosing type to work with.

It would be helpful if the SPAuthCallback is refactored to an Interface in the SPRequestHandler and the LoginActivity implements its own callback there to decouple both classes and allow custom login activities.

**Comment by bhariharan** [comment]
@methodus I could take a look at decoupling this in a future release. Some of the reliance on `LoginActivity` is intentional though - we expect custom login view controllers to extend `LoginActivity` and override the pieces they need to customize (both layout and functionality) as opposed to creating a new login view controller from scratch.

**Comment by wmathurin** [comment]
This issue is almost 4 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.
