### ISSUE TITLE
Android/iOS - Make login screenshots possible by configuration

### ISSUE THREAD

**Issue by ErnstEeldert** [forcedotcom/SalesforceMobileSDK-Android#1952]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 8.1
4. Device: Samsung XCover 4
5. Steps to reproduce: Start the application, which in turn shows the login activity. Try to make a screenshot.
6. Actual behavior: Screenshot is not taken.
7. Expected Behavior: It would be nice to be able to configure the app in such a way that screenshots of the login screen are possible. This would be useful for creating training materials.
8. Error Log: n/a

**Comment by brandonpage** [comment]
Hi @ErnstEeldert,

If you are consuming via source it would be very easily to make a one-off build that allows for screenshots.  In LoginActivity.java comment out the following code:

```
// Protect against screenshots.
getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE,  WindowManager.LayoutParams.FLAG_SECURE);
```

The same can be done for Passcode or any other activity.  However, because this is a security feature I do not think we want to put any kind of configuration toggle around it.
