### ISSUE TITLE
Login back issue - Unable to go back to previous activity 

### ISSUE THREAD

**Issue by bernardgarekani20** [forcedotcom/SalesforceMobileSDK-Android#1973]
Please fill out the following details:

1. Version of Mobile SDK Used: v7.1.2 
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: All
4. Device: All
5. Steps to reproduce: I have landing screen and there is a button to launch Login activity and that Login activity extends SalesforceActivity and now i want to return to LandingScreen by pressing back but it's resuming this Login page only.  
6. Actual behavior: Back button do nothing, I have tried to override the onBackpress method and try to kill Login activity but nothing seems working. 
7. Expected Behavior: It should jump to the previous backstack activity from which Login activity opened.
8. Error Log:

This issue is replication of 
[Click here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1956#issue-475135399
)

**Comment by bhariharan** [comment]
Thanks for reporting. We will take a look.

**Comment by brandonpage** [comment]
@bernardgarekani20 Have you implemented deferred login for your app? More info here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_native_deferred_login.htm

**Comment by wmathurin** [comment]
Old issue, last question was never answered. Closing.

**Comment by fm-eb** [comment]
I'd like to reopen this. The issue still persists 6 months later and by now you can find several ticket regarding this bug or related to this bug. Most of the time the dry answer is "use deferred login" with the link above from @brandonpage 

I just implemented the exact description of that link and was not suprised when there was still no going back to the `LauncherActivity`. As soon as any of the "LoginActivities" are involved, the user is completely stuck in this area. No matter if the back button is clicked, if the app goes in the background/foreground or any other action except for a complete app restart.

That such an important, basic functionality is not working is kind of ridiculous imho. 
On every issue here, I read allegedly explanations like

**1. The SDK is assuming that the whole app needs a login**
Why? I have a very very hard time to believe that this is really what "a vast majority of customers" want. This explanation might work for managers. As a developer it sounds to me more like "we realize that our choice of architecture was really not so good, but now we cannot change it anymore without re-writing the whole thing"

Looking at the code, it feels like looking at code from pre-Honeycomb Android. Activities everywhere. So much inheritance instead of composition. This is a perfect bad example for the outcome of "convenience inheritance". Back in the days this was arguably reasonable, because lifecycle management was tightly coupled with Activities. But that was like 7 years ago. Now we have LifecycleOwners, ViewModels, NavigationComponents....perfect, well-established tools for scenarios like this.

**2. You can override `fixBackButtonBehavior` to implement your own behaviour**
While you actually do give the developers a workaround for your already existing workarounds in `LoginActivity`, this does not help with the bug here. Regardless of returning true, false or calling any of the OS methods like `finish()` or `onBackPressed()`: The LoginActivity is always recreated immediately. The user is stuck in there.

Yes, as you might guess by now, I am quite frustrated with Salesforce, but unfortunately our client can't afford to switch anymore. So I hope that we can still figure out a solution together in this ticket. I am not blaming anyone. I want to fix this ticket.

_One step into the right direction would at least be that the documentation of deferred login gets changed so that it produces an actually usable example app._
