### ISSUE TITLE
NPE when calling SalesforceSDKManager.getInstance().getClientManager().peekRestClient(account)

### ISSUE THREAD

**Issue by afijal** [forcedotcom/SalesforceMobileSDK-Android#2043]
1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:9
4. Device: Samsung Galaxy Tab A 8.0
5. Steps to reproduce: call SalesforceSDKManager.getInstance().getClientManager().peekRestClient(account)
6. Actual behavior: App crashes
7. Expected Behavior: ResClient is returned
8. Error Log:
Fatal Exception: java.lang.NullPointerException
```
Attempt to invoke virtual method 'java.lang.String com.salesforce.androidsdk.accounts.UserAccount.getAccountName()' on a null object reference

com.salesforce.androidsdk.rest.ClientManager.peekRestClient (ClientManager.java:149)
org.verasolutions.promise3.sync.ResourceFileUploader.<init> (ResourceFileUploader.java:44)
```

```
Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException
No user account found
com.salesforce.androidsdk.rest.ClientManager.peekRestClient (ClientManager.java:154)
com.salesforce.androidsdk.rest.ClientManager.peekRestClient (ClientManager.java:138)
com.salesforce.androidsdk.rest.ClientManager.getRestClient (ClientManager.java:115)
com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume (SalesforceActivityDelegate.java:87)
com.salesforce.androidsdk.ui.SalesforceActivity.onResume (SalesforceActivity.java:54)
org.verasolutions.promise3.BaseActivity.onResume (BaseActivity.java:125)
```

**Comment by bhariharan** [comment]
The stack trace sums it up - you don't have a valid user account object, i.e. login is not complete. If you call `peekRestClient()`, it won't crash, but if you call `peekRestClient(account)`, passing in a `null` account, it will not work. Please take a look at our sample apps and templates on correct usage patterns for `peekRestClient()`. Also, please upgrade to the latest version (`8.1.0`) - the version you're on is quite old and we've put in many bug fixes and enhancements since then.
