### ISSUE TITLE
App close after login when the user swap apps in the middle of login

### ISSUE THREAD

**Issue by murilodag** [forcedotcom/SalesforceMobileSDK-Android#2070]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: All (android 8, 9, 10)
4. Device: All (pixels, motorollas)
5. Steps to reproduce: 
        a. Open app (unauthenticated)
        b. Click on "Sign In" button
        c. Enter credentials and hit enter
        d. Allow Access screen will appear
        e. Open some other application (For example Gallery)
        f. Go to the app again
        g. Click on Allow button
        h. Verify app is closed
6. Actual behavior: App closes and, on reopen, the user is logged in
7. Expected Behavior: The user should be logged in (without closing it)
8. Error Log: The are no error logs or crashes.

Similar issue with hybrid: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/444#issuecomment-473431734

**Comment by bhariharan** [comment]
@murilodag This is due to `singleTask` and is required for some other use cases/types of login. Please read the discussion [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/444#issuecomment-473431734). We do have overrides available in `LoginActivity` to override the default behavior. You are welcome to create a subclass of `LoginActivity` and tweak this behavior to suit your app.

**Comment by adnan-rolustech** [comment]
Version of Mobile SDK Used: 9.1.1
Issue found in Native App
OS Version: 11
Device: All Android Devices
App Created by using **forcedroid**

**Steps to reproduce issue:**
1 - Open the app ( Without logged in user / Un-authenticated )
2 - Proceed to login flow
3 - Enter the credentials
4 - Press the login button
5 - During the process press the back button or **minimize** the app.

**Expected Behavior:** 
The App should resumed where it was minimized

**App Behavior:** 
The App shows the login screen again and again even if we provide the user credentials again and again. The App goes into background, even if we logged in successfully.
Also if we kill the app and then came back the app shows that the user is already logged in.

Kindly provide a solution regarding this behavior. 
Thank You.
