### ISSUE TITLE
error code 8: attempt to write a readonly database

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2251]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.1.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 8
4. Device: TC-25
5. Steps to reproduce: logout while inserting in db
6. Actual behavior: crashed
7. Expected Behavior:
8. Error Log: error code 8: attempt to write a readonly database

**Comment by wmathurin** [comment]
On logout, we delete user databases which will lead to errors if the app is still writing to them.
Architect your application to stop accessing the databases before you trigger a logout. Or alternatively, you could handle the error gracefully by recognizing that the user is no longer logged in (instead of letting the exception bubble up and potentially crash your application).
