### ISSUE TITLE
Creating a custom login

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2291]
I'm having problems creating a custom Login activity class. Now, for some reason, after I log out and I try to login again the app reset back again to the login page. After that, I can log in again. Below, I will leave the class.

https://gist.github.com/johnjeremih/bae4d1a73745613a3ffb99c2ef21ec01#file-oauthactivity-kt

**Comment by wmathurin** [comment]
In your main application class, when you initialize the SalesforceSDKManager, are you calling [this](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java#L401) method and passing your login activity class.

**Comment by johnjeremih** [comment]
I know that. What I need to know is how I can create a login activity class. Do you guys have an example?

**Comment by wmathurin** [comment]
Subclass LoginActivity.java, make it use your own layout and have handlers for extra buttons etc it might have.

**Comment by johnjeremih** [comment]
@wmathurin I tried extending the class, but it doesn't work.

**Comment by johnjeremih** [comment]
@wmathurin  any ideas?

**Comment by gkotula** [comment]
Hi @johnjeremih, You can customize the login view in a couple of ways.  If you want to change what is shown in the `WebView` with the [instructions here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_customize_login.htm), or you can customize the layout of the native app by subclassing `LoginActivity` and inflating your custom layout XML.

**Comment by johnjeremih** [comment]
@gkotula that is just for iOS. Do you have a working example for Android?

**Comment by gkotula** [comment]
Hi @johnjeremih, apologies for the confusion with the link.  I meant to draw attention to the section titled "Customizing the Login Screen through the Salesforce Server".  Using My Domain and/or branded login pages is the recommended way to customize the look/feel of the login screen for both web and mobile.

If you cannot achieve the results you want using only the online branding tools, then customizing the login Activity itself is indeed possible; however, you must acknowledge that any customizations you make are outside the scope of our support. 
 If/when the official Salesforce `LoginActivity` changes, you are responsible for reconciling new version's changes with your local ones.

With that in mind, here are the steps to customize the `LoginActivity`:

1. Create a subclass of `LoginActivity` (e.g. `public class MyLoginActivity extends LoginActivity {...}`).
2. Create a copy the `sf__login.xml` layout file (bundled with the SDK) in your app's main `res/layout` resource directory.
3. Wherever you call `SalesforceSDKManager.initNative(context, MainActivity.class);`, change this to include your `MyLoginActivity.class` like so:  `SalesforceSDKManager.initNative(context, MainActivity.class, MyLoginActivity.class);`.

With those steps, you should have your own login Activity ready to customize.  You can add layout elements to your copy of `sf__login.xml`, but be sure to _not_ remove or change any of the elements from the original layout XML.  Also, as a reminder, always be sure to always call `super` methods if you override any methods so that all the built-in login functionality continues to work as expected.  E.g.:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState); // <<< Always call super in all overridden methods
    /* Your customization here... */
}```

**Comment by gkotula** [comment]
@johnjeremih Were you able to achieve the results you were looking for?

**Comment by johnjeremih** [comment]
Hi @gkotula  yes, the login part worked fine, but I can't change the status bar color. Also, the buttons that I added to the view don't respond, only the webview.

**Comment by gkotula** [comment]
@johnjeremih Apologies, but we can't help debug your custom Activity implementation as we do not have the resources to offer that level of support.  Mobile SDK is open source, so you are free to extend or alter any part of the SDK in your app; however, we offer no guarantees concerning any components your implementation has changed.

It sounds like you are able to create your custom Login Activity and use it in your app; is your original issue resolved?

**Comment by gkotula** [comment]
From your original post:

>Now, for some reason, after I log out and I try to login again the app reset back again to the login page. After that, I can log in again.

The original issue stated that your custom login activity was resetting after logging out/in.  If that issue is resolved, and your custom login activity is no longer exhibiting this behavior, then you have all the support we can give you regarding this issue.

My best guess for the status bar color is that a Material Theme property is overriding the color you are setting.  Theming in Android is convoluted, but we cannot offer support to that level of detail.

**Comment by wmathurin** [comment]
Closing issue - looks like the question was answered.
For more "how do I ..." type questions, we recommend you post on our [stackexchange](https://salesforce.stackexchange.com/) and tag mobilesdk.
