### ISSUE TITLE
Modify Consumer Key dynamically. 

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2356]
We are currently updating our sandbox Environment every 30 days and I would like to know if there is a way that we can update the consumer key that is used on the bootconfig.xml dynamically. It is a pain having to add another build every time there is an environment update. Any Ideas?

**Comment by bhariharan** [comment]
No, each mobile app has a 1:1 mapping with a connected app and can not be updated dynamically - this is by design. Updating the Sandbox environment shouldn't affect connected apps though, since every connected app is auto-propagated in every environment, so you shouldn't need to update the consumer key.

**Comment by johnjeremih** [comment]
We are refreshing the sandbox environment from the Prod environment. The consumer key changes everytime. Before was the Url and the consumer key, but now it is just the consumer key
