### ISSUE TITLE
In-app passcodes are not available and users is forced set up a lock screen

### ISSUE THREAD

**Issue by sidrabasit** [forcedotcom/SalesforceMobileSDK-Android#2366]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Android
3. OS Version: 12 
4. Device: Samsung Galaxy Note20
5. Steps to reproduce: 
a. There is no screen lock enabled by the user 
b. Open the Android mobile application and log in 
c. The user is redirected to the ScreenLockActivity
d. The user cannot proceed without enabling the screen lock 
7. Actual behavior: Users are forced to set up a lock screen and there is no way the user can choose the option of setting in-app passcode
8. Expected Behavior: When the user has not set a screen lock, the passcode screen to appear 
9. Error Log:

**Comment by brandonpage** [comment]
Hi @sidrabasit,

This sounds like it is working as designed since the behavior was changed last year.  Passcode/Screen Lock has always been an admin driven security feature and as such the user does not control it.  For improved security we now rely on the OS to handle the actual lock.  This should also be more convenient for end users as we received feedback from them about not wanting a separate, app specific, pin.
