### ISSUE TITLE
Able to login to the app when back button is clicked in Pin Code screen

### ISSUE THREAD

**Issue by rahulrkrish91** [forcedotcom/SalesforceMobileSDK-Android#2442]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 13
4. Device: Pixel 4
5. Steps to reproduce: Login to the app using pin code. Then kill the app and launch the app again and click on device back button
6. Actual behavior: App gets logged in
7. Expected Behavior: App should be closed
8. Error Log: N/A

**Comment by brandonpage** [comment]
Hi @rahulrkrish91, I just tried to reproduce this on a physical Pixel 4 running Android 13 and am unable to.  

Have you enabled the "Predictive back animations" feature in Developer options?

**Comment by brandonpage** [comment]
It has been two weeks with no response.  We can reopen this issue if it can still be reproduced without the "Predictive back animations" developer preview feature enabled.

**Comment by rahulrkrish91** [comment]
Hi @brandonpage, Sorry for the late response. The "Predictive back animations" is not enable in my device.

**Comment by brandonpage** [comment]
@rahulrkrish91 Is there any other info you can provide to help we reproduce the issue?  We have [overridden the back behavior in the activity](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/336334cdf6a8aca0dbada3bc79c0d6538a86413e/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ScreenLockActivity.java#L121) so that it should not be possible to back our of the screen. 

We will be updating how we handle back navigation in this activity in 11.1 when we officially add support Android 14.  However, if I am able to reproduce the issue on 13 and below I would want to get a fix for that our sooner.

**Comment by rahulrkrish91** [comment]
@brandonpage , I was able to reproduce this in Android 12 and 11 (emulator) the scenario that was mentioned. Will provide more info on this.
