### ISSUE TITLE
To Login directly to the application after resetting the password

### ISSUE THREAD

**Issue by malaynagarro** [forcedotcom/SalesforceMobileSDK-Android#2477]
1: Version of Mobile SDK Used: 11.0.1
2: Issue found in Native App or Hybrid App: Native Android App
3: OS Version: All Android device 
4:Device: All Android devices
5: Steps to reproduce: New or existing functionality
6: Actual behavior:
After resetting or create password the password, the application redirects to the login screen.
7: Expected Behavior:
After resetting or create the password, the application should not ask for login, It should redirect the user to the dashboard or a home screen. is there a way to achieve it via Salesforce SDK?
The user should be able to log in to the application with the newly reset password/ create password. Is there a way to assign access token to SFUsermanager it will fetch the user information needed so that we can continue using the application with login again
Error Log: NA

**Comment by brandonpage** [comment]
Hi @malaynagarro  The behavior you describe happens entirely within the webview, which the Mobile SDK unfortunately has no control over.  Regardless of what happens within the webview if the SDK does not get a callback with OAuth tokens we are not authenticated.  I am going to close the issue here, but if you want to pursue this further I would recommend reaching out to support through the standard channels so they can get the Core Authentication team involved.
